from ex1 import HealingCreatureFactory, TransformCreatureFactory

if __name__ == "__main__":
    print("Testing Creature with healing capability")
    print("base:")
    healing_creature = HealingCreatureFactory()
    sproutling = healing_creature.create_base()
    print(sproutling.describe())
    print(sproutling.attack())
    print(sproutling.heal())
    print("evolved:")
    bloomelle = healing_creature.create_evolved()
    print(bloomelle.describe())
    print(bloomelle.attack())
    print(bloomelle.heal())

    print()
    print("Testing Creature with transform capability")
    print("base:")
    transform_creature = TransformCreatureFactory()
    shiftling = transform_creature.create_base()
    print(shiftling.describe())
    print(shiftling.attack())
    print(shiftling.transform())
    print(shiftling.attack())
    print(shiftling.revert())
    print("evolved:")
    morphagon = transform_creature.create_evolved()
    print(morphagon.describe())
    print(morphagon.attack())
    print(morphagon.transform())
    print(morphagon.attack())
    print(morphagon.revert())
