server {
    listen       443 ssl;
    server_name  ahalifa.42.fr;

    root /var/www/htlm
    index index.php

    ssl_certificate /usr/nginx/ssl.crt;
    ssl_certificate_key /usr/nginx/ssl.key 
    ssl_password_file /usr/nginx/ssl.pass;   
    ssl_protocol TLSv1.3
    location / {
        fastcgi_pass wordpress:9000;

    }

}
